// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: asklouTimer

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Start
void ui_Start_screen_init(void);
lv_obj_t *ui_Start;
lv_obj_t *ui_StartArc;
lv_obj_t *ui_TimerLabel;
lv_obj_t *ui_PlayImgButton;
// CUSTOM VARIABLES


// SCREEN: ui_Pause
void ui_Pause_screen_init(void);
lv_obj_t *ui_Pause;
lv_obj_t *ui_PauseArc;
lv_obj_t *ui_PauseTimerLabel;
lv_obj_t *ui_PauseImageButton;
// CUSTOM VARIABLES


// SCREEN: ui_Rewind
void ui_Rewind_screen_init(void);
lv_obj_t *ui_Rewind;
lv_obj_t *ui_RewindArc;
lv_obj_t *ui_RewindTimerLabel;
lv_obj_t *ui_RewindImageButton;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Start_screen_init();
ui_Pause_screen_init();
ui_Rewind_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Start);
}
