// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: asklouTimer

#ifndef _ASKLOUTIMER_UI_H
#define _ASKLOUTIMER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Start
void ui_Start_screen_init(void);
extern lv_obj_t *ui_Start;
extern lv_obj_t *ui_StartArc;
extern lv_obj_t *ui_TimerLabel;
extern lv_obj_t *ui_PlayImgButton;
// CUSTOM VARIABLES

// SCREEN: ui_Pause
void ui_Pause_screen_init(void);
extern lv_obj_t *ui_Pause;
extern lv_obj_t *ui_PauseArc;
extern lv_obj_t *ui_PauseTimerLabel;
extern lv_obj_t *ui_PauseImageButton;
// CUSTOM VARIABLES

// SCREEN: ui_Rewind
void ui_Rewind_screen_init(void);
extern lv_obj_t *ui_Rewind;
extern lv_obj_t *ui_RewindArc;
extern lv_obj_t *ui_RewindTimerLabel;
extern lv_obj_t *ui_RewindImageButton;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_play_button_png);   // assets/play_button.png
LV_IMG_DECLARE( ui_img_pause_png);   // assets/pause.png
LV_IMG_DECLARE( ui_img_rewind_button_png);   // assets/rewind_button.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
