// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: asklouTimer
//Adjusted by Peter Machona 30 Dec
#ifndef UI_EVENTS_H
#define UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

/* Function prototypes for our event callbacks */
void PlayImgButton_event_cb(lv_event_t* e);
void PauseImageButton_event_cb(lv_event_t* e);
void RewindImageButton_event_cb(lv_event_t* e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
