// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: asklouTimer

#include "ui.h"

void ui_Pause_screen_init(void)
{
ui_Pause = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Pause, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PauseArc = lv_arc_create(ui_Pause);
lv_obj_set_width( ui_PauseArc, 225);
lv_obj_set_height( ui_PauseArc, 210);
lv_obj_set_x( ui_PauseArc, 8 );
lv_obj_set_y( ui_PauseArc, 1 );
lv_obj_set_align( ui_PauseArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_PauseArc, 50);

lv_obj_set_style_arc_color(ui_PauseArc, lv_color_hex(0x3BB77E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_PauseArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_PauseArc, lv_color_hex(0x3BB77E), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PauseArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_PauseTimerLabel = lv_label_create(ui_Pause);
lv_obj_set_width( ui_PauseTimerLabel, 39);
lv_obj_set_height( ui_PauseTimerLabel, LV_SIZE_CONTENT);   /// 25
lv_obj_set_x( ui_PauseTimerLabel, 1 );
lv_obj_set_y( ui_PauseTimerLabel, -6 );
lv_obj_set_align( ui_PauseTimerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_PauseTimerLabel,"00:00");

ui_PauseImageButton = lv_imgbtn_create(ui_Pause);
lv_imgbtn_set_src(ui_PauseImageButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_pause_png, NULL);
lv_obj_set_height( ui_PauseImageButton, 42);
lv_obj_set_width( ui_PauseImageButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_PauseImageButton, 0 );
lv_obj_set_y( ui_PauseImageButton, 64 );
lv_obj_set_align( ui_PauseImageButton, LV_ALIGN_CENTER );


}
