// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: asklouTimer

#include "ui.h"

void ui_Rewind_screen_init(void)
{
ui_Rewind = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Rewind, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_RewindArc = lv_arc_create(ui_Rewind);
lv_obj_set_width( ui_RewindArc, 225);
lv_obj_set_height( ui_RewindArc, 210);
lv_obj_set_x( ui_RewindArc, 8 );
lv_obj_set_y( ui_RewindArc, 1 );
lv_obj_set_align( ui_RewindArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_RewindArc, 50);

lv_obj_set_style_arc_color(ui_RewindArc, lv_color_hex(0x3BB77E), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_RewindArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_RewindArc, lv_color_hex(0x3BB77E), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RewindArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_RewindTimerLabel = lv_label_create(ui_Rewind);
lv_obj_set_width( ui_RewindTimerLabel, 39);
lv_obj_set_height( ui_RewindTimerLabel, LV_SIZE_CONTENT);   /// 25
lv_obj_set_x( ui_RewindTimerLabel, 1 );
lv_obj_set_y( ui_RewindTimerLabel, -6 );
lv_obj_set_align( ui_RewindTimerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RewindTimerLabel,"00:00");

ui_RewindImageButton = lv_imgbtn_create(ui_Rewind);
lv_imgbtn_set_src(ui_RewindImageButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_rewind_button_png, NULL);
lv_obj_set_height( ui_RewindImageButton, 64);
lv_obj_set_width( ui_RewindImageButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_RewindImageButton, 0 );
lv_obj_set_y( ui_RewindImageButton, 64 );
lv_obj_set_align( ui_RewindImageButton, LV_ALIGN_CENTER );


}
